name: Supabase Migrations

on:
  push:
    paths:
      - 'supabase/**'
      - '.github/workflows/supabase.yml'
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Supabase CLI
        run: |
          npm i -g supabase@2
      - name: Supabase diff (validate)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase --version
          supabase db lint || true
  package:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Supabase CLI
        run: npm i -g supabase@2
      - name: Package migrations
        run: |
          supabase db package -f supabase/migrations --repo supabase/migrations || true
